config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pigs/', include('pigs.urls')),
    path('users/', include('users.urls'))
]

pigs/urls.py
from django.urls import path
from . import views

app_name='pigs'

urlpatterns = [
    
    #path('', views.Home.as_view(), name='home')
    path('', views.home, name='home' ),
    path('about', views.about, name='about')
]

users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('home', views.home, name='home'),
    path('about', views.about, name='about')
]

users/models.py
from django.db import models

# Create your models here.

pigs/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DetailView, DeleteView

# Create your views here.

#con función
def home(request):
    return render(request, 'pigs/home.html')

#con class based views
# class Home(TemplateView):
#     template_name= 'home.html'

def about(request):
    return render(request, 'pigs/about.html')

users/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'users/home.html')
def about(request):
    return render(request, 'users/about.html')

pigs/templates/pigs/about.html
{% extends 'base.html' %}
{% block content %}
<h2>Pigs About</h2>
<a href="{% url 'pigs:home' %}">Pigs Home</a>

{% endblock %}

pigs/templates/pigs/home.html
{% extends 'base.html' %}
{% block content %}
<h2>Pigs</h2>
<a href="{% url 'pigs:about' %}">About</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>

    <title>Document</title>
</head>
<body>
    <nav>
        <ul>

            <li>
                
                <a href="{% url 'pigs:home' %}">home pigs desde base</a>
            </li>
            <li>
                
                <a href="{% url 'pigs:about' %}">about pigs desde base</a>
            </li>
            <li>
                <a href="{% url 'users:home' %}">home users desde base</a>
            </li>
            <li>
                <a href="{% url 'users:about' %}">about users desde base</a>
            </li>
        </ul>

    </nav>
    <h1>base general</h1>
    {% block content %}
    
    {% endblock %}
</body>
</html>

users/templates/users/about.html
{% extends 'base.html' %}
{% block content %}

<h2>Users about</h2>
{% endblock %}

users/templates/users/home.html
{% extends 'base.html' %}
{% block content %}
<H2>Users Home</H2>
<p class="bg-sky-500">Usando users home con tailwind</p>
{% endblock %}